export * from './not-found/NotFound.page';
export * from './panel/Panel.page';
export * from './login/Login.page';
export * from './register/Register.page';
export * from './books/Books.page';
export * from './collections/Collections.page';
export * from './upload/Upload.page';
export * from './settings/Settings.page';
export * from './profile/Profile.page';
